### ISSUE TITLE
Crash on Save with Apple M1

### ISSUE THREAD

**Issue by herve-ch** [libgdx/gdx-particle-editor#11]
Hello i have a crash and this error when i use "save as" on apple M1:

NSWindow geometry should only be modified on the main thread!

To fix it, in SaveAsRunnable.java,  I removed the ExecutorService and I have no more crash

**Comment by raeleus** [comment]
Thanks for the tip. I'll look at these issues in the next couple days. Thank you.

**Comment by raeleus** [comment]
Thanks for identifying the issue. I wouldn't have figured it out without your help. This should be resolved in the next version. It's hard for me to test, however. I don't have a Mac. Please reopen if it is not resolved.
