### ISSUE TITLE
Locate missing images issue

### ISSUE THREAD

**Issue by obigu** [libgdx/gdx-particle-editor#4]
Here's a particle effect file I'm testing that doesn't have an absolute path to the image it uses, just the name of the image (bombparticle.png) like the following:
 
[bomb.txt](https://github.com/libgdx/gdx-particle-editor/files/13477464/bomb.txt)

I don't store the particle images alongside the effects, so, when trying to open it it says it can't find the images which is Ok. On the old Particle editor the effect would open and you'd need to locate the image you want if you wanted to visualize it. On this new version, a dialog pops up telling you to locate the images, when clicking on the `Locate images...` button I think there's a bug because it doesn't show just the images but a list with all the elements of the particle effect.

![image](https://github.com/libgdx/gdx-particle-editor/assets/1794492/7264d75f-1f43-436f-9ad9-6db1569c17db)

I haven't got past this step because I would need to locate images for all elements but it also says images will be copied to that folder which is not something I want (maybe make it optional?).

**Comment by raeleus** [comment]
You've found a number of bugs! I have fixes for these in the next version. I will no longer copy the files to the particle effect directory in the Locate Images dialog and there is a setting to disable copying the images on save as well. Thank you so much.
