### ISSUE TITLE
UX and enhancement ideas

### ISSUE THREAD

**Issue by NathanSweet** [libgdx/gdx-particle-editor#8]
I needed a particle effect so finally got a chance to use the editor for real! Some notes on my experience:

* The preview (background) image goes over the statistics and particle view buttons: ![](http://n4te.com/x/321-2txw.png) They can still be clicked, just not seen. Not seeing the statistics hurts. For now I pan my (very large) background image off screen then back again.
* It would be helpful to be able to see the effect without dimming while changing the color. Maybe don't dim when the color dialog is open, or dim everything except the particle view? Eg by drawing a few translucent rectangles instead of one big one.
* I'd love a way to reload all particle images. Currently I close the app and reopen, then need to load my particles, background image, view sizes.
* I find myself scanning the properties a lot to find the one I want. Eg, I know I want "velocity" -- which set of controls is velocity? The background color behind the tabs is the same color as the tab contents, so it's hard for my eyes to quickly check each tab name. It might be better for the background behind the tabbed sections to be darker (not sure how to handle all the sections being inside the `Emitter Properties` tab). It would also help to have an icon for each section, with distinct silhouettes/colors.
* Graph handles jump when the drag exits the tap square. If you reset the "touchdown" position to the tap square exit position, more precise control of the the handle manipulation would be possible.
* Could note in the tooltip that it's slightly more work when `Attached` is checked (translates all particles).
* New images go to the bottom of the list, needs a lot of up clicks to make them current. Maybe add them second?
* I just noticed the dragging in the images list, cool! DragScrollListener can make it usable even when the list scrolls.
* My app runs at 60Hz while the editor runs at 144Hz. It took me a while to figure out why the particles were different around the emitter position. It'd be nice if I could set a frame rate cap in the editor, so I can see exactly the same as the app.

Sorry for being a _filthy user_ rather than contributing, but it's all the time I have at the moment!

**Comment by raeleus** [comment]
These are all great points. I'll work on them in the coming weeks. Thank you for taking the time!

**Comment by raeleus** [comment]
Yes, every one of these suggestions was a good choice to implement. I have included your suggestions in the latest version, @NathanSweet: https://github.com/libgdx/gdx-particle-editor/releases/tag/1.0.7

**Comment by raeleus** [comment]
Oh, just realized I forgot to add icons. I'll keep that filed away for another update.

**Comment by NathanSweet** [comment]
Super cool, thanks for all your hard work!
